name: Dev Environment
description: File suggestion that relates to the developer environment
title: "[Dev Env]: "
labels: ["üõ†Ô∏èdev env"]
body:
  - type: dropdown
    id: aspect
    attributes:
      label: aspect
      description: What aspect of the dev env does this relate to?
      multiple: true
      options:
        - Linting
        - Testing
        - Running in development
        - VSCode
        - Storybook
        - Turborepo
        - Design
        - Continous Integration
        - Continous Deployment
        - GitHub
        - Other
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Suggestion?
      description: What changes would you like to see?
      placeholder: Please make the tests run faster
    validations:
      required: true
  - type: textarea
    id: possible-solutions
    attributes:
      label: Possible Solutions
      description: Got ideas for how to solve this?
      placeholder: Use SQLLite while testing
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: Extra Information
      description: Post any extra links, screenshots, or references that might be helpful here
      placeholder: Check out this for how the tests should be implemented https://www.youtube.com/watch?v=dQw4w9WgXcQ
    validations:
      required: false
