"ğŸ¤–bot":
  - any: ["apps/discord-bot/**"]

"ğŸ“¢ command":
  - any: ["apps/discord-bot/src/commands/**"]

"ğŸ“–bot-ui":
  - any: ["apps/discord-bot/src/components/**"]

"ğŸ†event":
  - any: ["apps/discord-bot/src/listeners/**"]

"âš¡ api":
  - any: ["packages/api/**"]

"ğŸ”’auth":
  - any: ["packages/auth/**"]

"âš› component":
  - any: ["packages/ui/src/components/**"]

"ğŸ“šdb":
  - any: ["packages/db/**"]

"ğŸ“„ page":
  - any: ["apps/nextjs/src/pages"]

"ğŸ–¥ï¸website":
  - any: ["packages/ui/**", "apps/nextjs/**"]
